basePath: /api
host: localhost
info:
  contact:
    email: chg3376@gmail.com
    name: Request permission of game API
    url: http://github.com/hangyuCho
  description: This is a game api server
  license: {}
  title: GAME API
  version: 0.0.1
paths: {}
swagger: "2.0"
