// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2021-08-14 20:51:52.003933 +0900 JST m=+0.132603936

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This is a game api server",
        "title": "GAME API",
        "contact": {
            "name": "Request permission of game API",
            "url": "http://github.com/hangyuCho",
            "email": "chg3376@gmail.com"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "0.0.1"
    },
    "host": "localhost",
    "basePath": "/api",
    "paths": {
        "/api/hello": {
            "get": {
                "description": "game API 상세",
                "consumes": [
                    "application/x-json-stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "필요 없습니다.",
                        "name": "none",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/hello": {
            "get": {
                "description": "game API 상세",
                "consumes": [
                    "application/x-json-stream"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "필요 없습니다.",
                        "name": "none",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
